#include<iostream>
using namespace std;
main(){
int num1;
int num2;
int num3;
int num4;
int num5;
int num6;
int num7;
int num8;
int num9;
int num10;
int num11;
int num12;
int num13;
int num14;
int num15;
cout<<"Enter 1 number :";
cin>>num1;
cout<<"Enter 2 number :";
cin>>num2;
cout<<"Enter 3 number :";
cin>>num3;
cout<<"Enter 4 number :";
cin>>num4;
cout<<"Enter 5 number :";
cin>>num5;
cout<<"Enter 6 number :";
cin>>num6;
cout<<"Enter 7 number :";
cin>>num7;
cout<<"Enter 8 number :";
cin>>num8;
cout<<"Enter 9 number :";
cin>>num9;
cout<<"Enter 10 number :";
cin>>num10;
cout<<"Enter 11 number :";
cin>>num11;
cout<<"Enter 12 number :";
cin>>num12;
cout<<"Enter 13 number :";
cin>>num13;
cout<<"Enter 14 number :";
cin>>num14;
cout<<"Enter 15 number :";
cin>>num15;
float total;
total = (num1+num2+num3+num4+num5) + (num6*num7*num8*num9*num10) - (num11-num12-num13-num14-num15);
cout<<"The Total is :"<<total;
}